@echo off
REM Auto-generated by scripts/restart-expo.ps1 - do not edit by hand.
cd /d "C:\Users\Public\multiptabwatsap\mobile"
set EXPO_NO_TELEMETRY=1
set REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.12
set EXPO_PACKAGER_HOSTNAME=192.168.1.12
set EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
echo ------------------------------------------------------------
 echo  Metro will advertise:  exp://192.168.1.12:19000
 echo  REACT_NATIVE_PACKAGER_HOSTNAME = %REACT_NATIVE_PACKAGER_HOSTNAME%
echo ------------------------------------------------------------
call npx --no-install expo start --lan --port 19000 --clear
echo.
echo (Expo exited. Press any key to close this window.)
pause >nul
